#ifndef opcode_h
#define opcode_h

enum OpCode {
    OP_return=0,
    OP_true=1,
    OP_false=2,
    OP_pop=3,
    OP_pop_n=4,
    OP_loadEmbeddedByteConstant=5,
    OP_loadEmbeddedLongConstant=6,
    OP_loadEmbeddedExplicitlyTypedConstant=7,
    OP_loadConstantFromTable=8,
    OP_LONG_loadConstantFromTable=9,
    OP_negateInt=10,
    OP_negateDouble=11,
    OP_notBool=12,
    OP_greaterInt=13,
    OP_greaterDouble=14,
    OP_greaterString=15,
    OP_greaterOrEqualInt=16,
    OP_greaterOrEqualDouble=17,
    OP_greaterOrEqualString=18,
    OP_lessInt=19,
    OP_lessDouble=20,
    OP_lessString=21,
    OP_lessOrEqualInt=22,
    OP_lessOrEqualDouble=23,
    OP_lessOrEqualString=24,
    OP_equalEqualInt=25,
    OP_equalEqualDouble=26,
    OP_equalEqualString=27,
    OP_equalEqualBool=28,
    OP_notEqualInt=29,
    OP_notEqualDouble=30,
    OP_notEqualString=31,
    OP_notEqualBool=32,
    OP_minusInt=33,
    OP_minusDouble=34,
    OP_divideInt=35,
    OP_divideDouble=36,
    OP_multiplyInt=37,
    OP_multiplyDouble=38,
    OP_intDivideInt=39,
    OP_intDivideDouble=40,
    OP_modInt=41,
    OP_addInt=42,
    OP_addDouble=43,
    OP_addString=44,
    OP_orBool=45,
    OP_andBool=46,
    OP_outputInt=47,
    OP_outputDouble=48,
    OP_outputBoolean=49,
    OP_outputString=50,
    OP_outputArray=51,
    OP_outputAny=52,
    OP_outputClass=53,
    OP_outputVoid=54,
};

#endif /* opcode_h */